DATA:
   input_path: /data/raw/ <user input required- specify full input path + filename for raw data>

   output_path: /data/preprocessed <user input required- specify full output path for preprocessed data>
MODEL:
   model_path: /models/ <user input required- specify full path to store model files>